# Generated by Django 5.1.2 on 2024-10-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messaging', '0001_initial'),
        ('profiles', '0002_profile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to='profiles.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
