# Generated by Django 5.1.2 on 2024-10-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_users_is_verified_users_verification_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
